services:
  nginx:
    # container config
    container_name: nginx_server
    # image config
    # image: nginx:latest
    # build config
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.staging
      args:
        - VERSION=1.2.3.4
    ports:
      - 8000:80
    environment:
      - SPED=900
      - RATE_LIMIT=true
    depends_on:
      - postgresql

  nodejs:
    container_name: nodejs_app
    build:
      context:  ./docker/nodejs
      dockerfile: Dockerfile.staging
    ports:
      - 3001:3000
    depends_on:
      - postgresql
      - nginx

  postgresql:
    container_name: postgresql_db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    